"""create like, matches and conversations tables

Revision ID: 81c9a2390e57
Revises: 7a7e839893af
Create Date: 2026-01-29 07:13:57.712629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c9a2390e57'
down_revision: Union[str, Sequence[str], None] = '7a7e839893af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_user_match')
    )
    op.create_table('card_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=False),
    sa.Column('to_card_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_card_id', name='uq_card_like')
    )
    op.create_table('chats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fk_conv_match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_conv_match_id'], ['user_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.add_column('chat_messages', sa.Column('fk_message_chat_id', sa.UUID(), nullable=False))
    op.add_column('chat_messages', sa.Column('fk_message_sender_id', sa.Integer(), nullable=False))
    op.add_column('chat_messages', sa.Column('fk_message_receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chat_messages_sender_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_constraint(op.f('chat_messages_receiver_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'users', ['fk_message_receiver_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'chats', ['fk_message_chat_id'], ['id'])
    op.create_foreign_key(None, 'chat_messages', 'users', ['fk_message_sender_id'], ['id'])
    op.drop_column('chat_messages', 'sender_id')
    op.drop_column('chat_messages', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_receiver_id_fkey'), 'chat_messages', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('chat_messages_sender_id_fkey'), 'chat_messages', 'users', ['sender_id'], ['id'])
    op.drop_column('chat_messages', 'fk_message_receiver_id')
    op.drop_column('chat_messages', 'fk_message_sender_id')
    op.drop_column('chat_messages', 'fk_message_chat_id')
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_table('card_likes')
    op.drop_table('user_matches')
    # ### end Alembic commands ###
