"""create zoom meetings service

Revision ID: b41cdd921d4f
Revises: bb21855e9332
Create Date: 2026-01-28 16:14:47.342128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41cdd921d4f'
down_revision: Union[str, Sequence[str], None] = 'bb21855e9332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoom_meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('join_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zoom_meetings')
    # ### end Alembic commands ###
